[package]

name = "dnd"
version = "0.0.1"
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]

[dependencies.irc]

irc = "~0.1.0"

[dependencies.crypto]

git = "https://github.com/seb-m/crypto.rs.git"
